### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [markfoodyburton/covid-bestfit#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data framehttp://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/BFS06W
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by markfoodyburton** [comment]
Hi, thanks for this.
Before adding the meta info, perhaps we should make sure that this makes sense. This really was/is "just a toy". It seems to be making some level of 'prediction' (predicting upticks in the French numbers), but it would need more work to be useful. The only real 'take aways' are:
a) There are a lot of independent variables - having clinical evidence for some of them would narrow the search and make the model more useful.
b) The 'Google mobility' data seems to be a reasonable proxy for the 'R' number  - but this isn't a huge surprise.

On the general point, please be in touch, and I'll happily help.

**Comment by reeshmabijosh** [comment]
Hello, Mark Burton

Great,  thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
I’ll give you the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.”

Thanks
Reeshma K
